### ISSUE TITLE
Port scripts to `augur curate`

### ISSUE THREAD

**Issue by joverlee521** [nextstrain/ingest#43]
To reduce the need to vendor ingest scripts and the need to document the vendoring process, I am prioritizing porting curation scripts in this repo into `augur curate` subcommands. 

To prevent blockers, I am aiming to port over the scripts _as is_ with the addition of **tests** in augur. 

### TODOs

- [x] https://github.com/nextstrain/augur/issues/1003
- [x] https://github.com/nextstrain/augur/issues/1482
- [x] https://github.com/nextstrain/augur/issues/1483
- [x] https://github.com/nextstrain/augur/issues/1484
- [x] https://github.com/nextstrain/augur/issues/1485
- [x] https://github.com/nextstrain/augur/issues/1486
- [x] Release new version of Augur with the new curate subcommands

### Post clean-up 

- Update [repos using the vendored scripts](https://github.com/search?type=code&q=org%3Anextstrain+subrepo+%22remote+%3D+https%3A%2F%2Fgithub.com%2Fnextstrain%2Fingest%22) to use the new `augur curate` commands. Listed individual issues below in order of importance:

    1. https://github.com/nextstrain/pathogen-repo-guide/issues/49
    2. https://github.com/nextstrain/zika/issues/68
    3. https://github.com/nextstrain/mpox/issues/262
    4. https://github.com/nextstrain/measles/issues/44
    5. https://github.com/nextstrain/dengue/issues/74
    6. https://github.com/nextstrain/seasonal-cov/issues/26
    7. https://github.com/nextstrain/rsv/issues/67
    8. https://github.com/nextstrain/avian-flu/issues/67
    9. https://github.com/nextstrain/yellow-fever/issues/8
    10. https://github.com/nextstrain/rabies/issues/1
    11. https://github.com/nextstrain/ncov-ingest/issues/454
    12. https://github.com/nextstrain/forecasts-ncov/issues/103
    13. https://github.com/nextstrain/hbv/issues/15

- https://github.com/nextstrain/docs.nextstrain.org/issues/212
- https://github.com/nextstrain/ingest/issues/44

**Comment by joverlee521** [comment]
Closing this issue since we are done with porting scripts to augur curate. 
There are still remaining pathogen repos that can be migrated, but they can be done in the future.
