### ISSUE TITLE
notify-slack: Migrate away from `files.upload`

### ISSUE THREAD

**Issue by joverlee521** [nextstrain/ingest#46]
Per [Slack's notification](https://bedfordlab.slack.com/files/USLACKBOT/F07M7QEUVHR/fwd__slack_app_developer_notice__upcoming_changes_to_support_for_the_files.upload_api_method)

> March 11, 2025
> 
> • Support for the files.upload API will be discontinued.
> 
> To prepare for this change, we recommend migrating away from files.upload and instead using the combination of [files.getUploadURLExternal](https://api.slack.com/methods/files.getUploadURLExternal) and [files.completeUploadExternal](https://api.slack.com/methods/files.completeUploadExternal). More information on how to use these two APIs together can be found on our [Working with files documentation](https://api.slack.com/messaging/files). You can also leverage Slack's SDKs to help you transition to this new way of uploading files by visiting our [api.slack page](https://api.slack.com/messaging/files#uploading_files).

### TODOs
- [x] merge https://github.com/nextstrain/ingest/pull/47
- [x] update pathogen repos to use channel id for `SLACK_CHANNELS` envvar
    - [x] org envvar `TEST_SLACK_CHANNEL` is already the channel id 
    - [x] forecasts-ncov - `SLACK_CHANNELS` already using channel id
    - [x] mpox - `SLACK_CHANNELS` already using channel id
    - [x] ~ncov - `slack_channel` in multiple builds.yaml~ ncov [does **not** use the files.upload API](https://github.com/nextstrain/ncov/blob/bc5100ba3f3630f64c1d65232debc3ba832417a9/workflow/snakemake_rules/export_for_nextstrain.smk#L417-L418)
    - [x] https://github.com/nextstrain/ncov-ingest/pull/492
- [x] update vendored scripts in pathogen repos 
    - [x] https://github.com/nextstrain/ncov-ingest/pull/494
    - [x] https://github.com/nextstrain/forecasts-ncov/pull/130
    - [x] https://github.com/nextstrain/mpox/pull/305

**Comment by joverlee521** [comment]
Just got another email about this today, I'll put it on my TODO's for the next two weeks.

**Comment by joverlee521** [comment]
Updated the pathogen repos that actively use the Slack notification scripts, leaving the others for now.
